In [24]:
import pandas as pd

In [25]:
data=pd.read_csv('/home/ubuntu-wasim/Documents/machineLearningMatrial/CarPrice_Prediction.csv')
data.head()

,9,1,audi 4000,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
0,10,0,audi 5000s (diesel),gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160.0,5500.0,16,22,NaN
1,11,2,bmw 320i,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101.0,5800.0,23,29,16430.0
2,12,0,bmw 320i,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101.0,5800.0,23,29,16925.0
3,13,0,bmw x1,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,NaN,3.19,9.0,121.0,4250.0,21,28,20970.0
4,14,0,bmw x3,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121.0,4250.0,21,28,21105.0

In [26]:
import os
print(os.getcwd())

/home/ubuntu-wasim/Documents/MachinelearningCode

In [8]:
type(data)

pandas.core.frame.DataFrame

In [27]:
data.columns

Index(['9', '1', 'audi 4000', 'gas', 'turbo', 'four', 'sedan', 'fwd', 'front',
       '105.8', '192.7', '71.4', '55.9', '3086', 'ohc', 'five', '131', 'mpfi',
       '3.13', '3.4', '8.3', '140', '5500', '17', '20', '23875'],
      dtype='object')

In [28]:
data.keys()

Index(['9', '1', 'audi 4000', 'gas', 'turbo', 'four', 'sedan', 'fwd', 'front',
       '105.8', '192.7', '71.4', '55.9', '3086', 'ohc', 'five', '131', 'mpfi',
       '3.13', '3.4', '8.3', '140', '5500', '17', '20', '23875'],
      dtype='object')

In [29]:
pd.read_csv('/home/ubuntu-wasim/Documents/machineLearningMatrial/CarPrice_Prediction.csv' , nrows=2)

,9,1,audi 4000,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
0,10,0,audi 5000s (diesel),gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.4,7.0,160,5500,16,22,NaN
1,11,2,bmw 320i,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.8,8.8,101,5800,23,29,16430.0

In [30]:
pd.read_csv('/home/ubuntu-wasim/Documents/machineLearningMatrial/CarPrice_Prediction.csv',usecols=[0,3])

       9     gas
0     10     gas
1     11     gas
2     12     gas
3     13     gas
4     14     gas
..   ...     ...
191  201     gas
192  202     gas
193  203     gas
194  204  diesel
195  205     gas

[196 rows x 2 columns]

In [31]:
pd.read_csv('/home/ubuntu-wasim/Documents/machineLearningMatrial/CarPrice_Prediction.csv',skiprows=[0])

,10,0,audi 5000s (diesel),gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.4,7,160,5500,16,22,Unnamed: 25
0,11,2,bmw 320i,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101.0,5800.0,23,29,16430.0
1,12,0,bmw 320i,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101.0,5800.0,23,29,16925.0
2,13,0,bmw x1,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,NaN,3.19,9.0,121.0,4250.0,21,28,20970.0
3,14,0,bmw x3,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121.0,4250.0,21,28,21105.0
4,15,1,bmw z4,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121.0,4250.0,20,25,24565.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
191,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
192,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
193,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
194,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

#header

change dtype

In [32]:
pd.read_csv('/home/ubuntu-wasim/Documents/machineLearningMatrial/CarPrice_Prediction.csv',dtype={'car_ID': 'float32'})

,9,1,audi 4000,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
0,10,0,audi 5000s (diesel),gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160.0,5500.0,16,22,NaN
1,11,2,bmw 320i,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101.0,5800.0,23,29,16430.0
2,12,0,bmw 320i,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101.0,5800.0,23,29,16925.0
3,13,0,bmw x1,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,NaN,3.19,9.0,121.0,4250.0,21,28,20970.0
4,14,0,bmw x3,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121.0,4250.0,21,28,21105.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
192,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
193,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
194,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
195,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

true_false=['yes']
false_value=['No']

Handling missing value in python

In [33]:
df = pd.read_csv('/home/ubuntu-wasim/Documents/machineLearningMatrial/CarPrice_Prediction.csv')
df.head()

,9,1,audi 4000,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
0,10,0,audi 5000s (diesel),gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160.0,5500.0,16,22,NaN
1,11,2,bmw 320i,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101.0,5800.0,23,29,16430.0
2,12,0,bmw 320i,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101.0,5800.0,23,29,16925.0
3,13,0,bmw x1,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,NaN,3.19,9.0,121.0,4250.0,21,28,20970.0
4,14,0,bmw x3,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121.0,4250.0,21,28,21105.0

In [34]:
df.isnull().sum().sum()

19

In [35]:
df.isnull().sum()

9            0
1            0
audi 4000    0
gas          0
turbo        0
four         0
sedan        0
fwd          0
front        0
105.8        1
192.7        1
71.4         0
55.9         2
3086         4
ohc          0
five         0
131          0
mpfi         0
3.13         4
3.4          0
8.3          0
140          1
5500         2
17           0
20           0
23875        4
dtype: int64